name: Issue
on:
  issues:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Issues
        uses: backstage/actions/issue-sync@140a9d5d2fcdb2c97aa7c435bf67834a9fb42bc9 # ratchet:backstage/actions/issue-sync@v0.6.2
