name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}

    steps:
      - uses: backstage/actions/pr-sync@140a9d5d2fcdb2c97aa7c435bf67834a9fb42bc9 # ratchet:backstage/actions/pr-sync@v0.6.2
        with:
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN  }}
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.BACKSTAGE_GOALIE_INSTALLATION_ID }}
          project-id: PVT_kwDOBFKqdc02LQ
          auto-assign: false
          excluded-users: freben
          owning-teams: '@backstage/techdocs'
